# Generated by Django 4.0.4 on 2022-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firtsName',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
